description: Prepares the repo for a typical CI job

name: Prepare

runs:
  steps:
    - uses: pnpm/action-setup@v4.2.0
      with:
        version: 10.26.1
    - uses: actions/setup-node@v6.1.0
      with:
        node-version: '24.12.0'
        cache: pnpm
    - run: pnpm install
      shell: bash
  using: composite